import type { DentalDemoTemplate } from "../types";

export const mexicoDentalProfile: DentalDemoTemplate = {
  id: "dental-clinic-mexico",
  country: "MX",
  countryName: "México",
  flag: "🇲🇽",
  orgName: "Clínica Dental México",
  legalName: "Clínica Dental México S.A. de C.V.",
  slug: "clinica-dental-mexico",
  locale: "es",
  timezone: "America/Mexico_City",
  currency: "MXN",
  scenario: {
    title: "Clínica Odontológica Especializada CDMX",
    description: "Demostración comercial para consultorios y clínicas en México: gestión multiespecialidad con WhatsApp, seguimiento de cotizaciones y citas de ortodoncia/implantes.",
    keyHighlights: [
      "Inbox WhatsApp con prospecto nuevo, cotización en negociación y paciente en revisión",
      "Pipeline adaptado a tiempos de decisión y financiamiento en pesos mexicanos",
      "Agenda con 3 citas futuras y 1 consulta concluida entre 3 doctores especialistas",
    ],
  },
  users: [
    {
      key: "owner",
      name: "Dr. Alejandro Morales",
      email: "alejandro@dentalmexico.demo",
      role: "admin",
      isProvider: true,
      title: "Director Clínico & Odontólogo",
    },
    {
      key: "operator",
      name: "Valeria Ramos",
      email: "valeria@dentalmexico.demo",
      role: "agent",
      isProvider: false,
      title: "Coordinadora de Pacientes",
    },
    {
      key: "dentist1",
      name: "Dr. Roberto Sánchez",
      email: "roberto@dentalmexico.demo",
      role: "agent",
      isProvider: true,
      title: "Especialista en Ortodoncia",
    },
    {
      key: "dentist2",
      name: "Dra. Elena Cruz",
      email: "elena@dentalmexico.demo",
      role: "agent",
      isProvider: true,
      title: "Especialista en Rehabilitación Oral",
    },
  ],
  services: [
    { name: "Valoración inicial y diagnóstico", slug: "consulta-inicial", durationMinutes: 30, description: "Evaluación clínica integral y radiografías", color: "#0284c7" },
    { name: "Profilaxis y limpieza ultrasónica", slug: "limpieza-dental", durationMinutes: 60, description: "Limpieza profesional profunda y pulido", color: "#10b981" },
    { name: "Aclaramiento dental profesional", slug: "blanqueamiento-dental", durationMinutes: 90, description: "Aclaramiento estético de alta gama en clínica", color: "#f59e0b" },
    { name: "Implante dental oseointegrado", slug: "implante-dental", durationMinutes: 120, description: "Fase quirúrgica de colocación de implante", color: "#6366f1" },
    { name: "Control y ajuste de ortodoncia", slug: "control-post-tratamiento", durationMinutes: 30, description: "Revisión mensual de brackets o alineadores", color: "#64748b" },
  ],
  pipeline: {
    name: "Tratamientos Odontológicos",
    slug: "tratamientos-odontologicos",
    stages: [
      { name: "Nuevo contacto", slug: "nuevo_contacto", position: 1 },
      { name: "Primera conversación", slug: "primera_conversacion", position: 2 },
      { name: "Interesado", slug: "interesado", position: 3 },
      { name: "Consulta agendada", slug: "consulta_agendada", position: 4 },
      { name: "Tratamiento vendido", slug: "tratamiento_vendido", position: 5, isWon: true },
      { name: "Paciente recurrente", slug: "paciente_recurrente", position: 6, isWon: true },
    ],
  },
  contacts: [
    {
      name: "Mateo Hernández",
      phoneNumber: "+525512345678",
      email: "mateo.hernandez@example.mx",
      status: "new",
      stageSlug: "nuevo_contacto",
      interest: "Aclaramiento dental",
      tags: ["aclaramiento", "prospecto-nuevo"],
      conversationMessages: [
        { direction: "inbound", body: "Buenas tardes, me gustaría información sobre costos y disponibilidad para un aclaramiento dental en la sucursal Roma Norte.", hoursAgo: 3 },
        { direction: "outbound", body: "¡Hola Mateo! Un gusto saludarte. En Clínica Dental México utilizamos tecnología láser de última generación con excelentes resultados en una sola sesión. ¿Qué día te gustaría agendar tu valoración sin costo?", hoursAgo: 2.5 },
        { direction: "inbound", body: "Me gustaría el próximo martes por la mañana con el Dr. Alejandro Morales.", hoursAgo: 2 },
      ],
    },
    {
      name: "Ximena Flores",
      phoneNumber: "+525598765432",
      email: "ximena.flores@example.mx",
      status: "new",
      stageSlug: "interesado",
      interest: "Tratamiento de Ortodoncia Invisible",
      tags: ["ortodoncia", "negociacion-activa"],
      conversationMessages: [
        { direction: "inbound", body: "Hola, ya me realizaron el escaneo 3D para los alineadores invisibles. ¿Tienen disponible el plan a meses sin intereses?", hoursAgo: 24 },
        { direction: "outbound", body: "Hola Ximena, con gusto. El Dr. Roberto Sánchez revisó tu plan digital y tenemos esquemas de 6 y 12 MSI con todas las tarjetas bancarias.", hoursAgo: 18 },
        { direction: "inbound", body: "Excelente, voy a revisar el presupuesto final con mi esposo y mañana les confirmo la fecha de inicio.", hoursAgo: 10 },
      ],
    },
    {
      name: "Santiago Navarro",
      phoneNumber: "+525588776655",
      email: "santiago.navarro@example.mx",
      status: "won",
      stageSlug: "paciente_recurrente",
      interest: "Revisión semestral",
      tags: ["paciente-frecuente", "mantenimiento"],
      conversationMessages: [
        { direction: "inbound", body: "Hola Valeria, ya cumplí 6 meses desde mi limpieza y me gustaría agendar cita con la Dra. Elena Cruz.", hoursAgo: 48 },
        { direction: "outbound", body: "¡Hola Santiago! Qué gusto saber de ti. Te confirmamos tu espacio para profilaxis con la Dra. Elena.", hoursAgo: 46 },
        { direction: "inbound", body: "Perfecto, nos vemos entonces. Muchas gracias.", hoursAgo: 40 },
      ],
    },
  ],
  appointments: [
    {
      eventTypeSlug: "consulta-inicial",
      patientName: "Mateo Hernández",
      providerKey: "owner",
      daysOffset: 1,
      localHour: 10,
      localMinute: 0,
      durationMinutes: 30,
      status: "confirmed",
      notes: "Consulta diagnóstica inicial para aclaramiento con Dr. Alejandro Morales.",
    },
    {
      eventTypeSlug: "control-post-tratamiento",
      patientName: "Ximena Flores",
      providerKey: "dentist1",
      daysOffset: 3,
      localHour: 11,
      localMinute: 30,
      durationMinutes: 30,
      status: "scheduled",
      notes: "Entrega y ajuste de alineadores de ortodoncia con Dr. Roberto Sánchez.",
    },
    {
      eventTypeSlug: "limpieza-dental",
      patientName: "Santiago Navarro",
      providerKey: "dentist2",
      daysOffset: 5,
      localHour: 16,
      localMinute: 0,
      durationMinutes: 60,
      status: "scheduled",
      notes: "Profilaxis semestral y pulido dental con Dra. Elena Cruz.",
    },
    {
      eventTypeSlug: "limpieza-dental",
      patientName: "Santiago Navarro",
      providerKey: "dentist2",
      daysOffset: -180,
      localHour: 12,
      localMinute: 0,
      durationMinutes: 60,
      status: "completed",
      notes: "Profilaxis anterior completada satisfactoriamente por Dra. Elena Cruz.",
    },
  ],
};

export default mexicoDentalProfile;
