import type { DentalDemoTemplate } from "../types";

export const portugalDentalProfile: DentalDemoTemplate = {
  id: "dental-clinic-portugal",
  country: "PT",
  countryName: "Portugal",
  flag: "🇵🇹",
  orgName: "Clínica Saúde Lisboa",
  legalName: "Clínica Saúde Lisboa, Lda.",
  slug: "clinica-saude-lisboa",
  locale: "pt-PT",
  timezone: "Europe/Lisbon",
  currency: "EUR",
  scenario: {
    title: "Clínica de Medicina Dentária em Lisboa",
    description: "Demonstração comercial para clínicas médicas e dentárias em Portugal: atendimento multicanal via WhatsApp, qualificação de novos tratamentos e agenda médica completa.",
    keyHighlights: [
      "Inbox WhatsApp com conversas sintéticas em português europeu",
      "Funil de conversão adaptado a tratamentos de reabilitação oral e estética",
      "Agenda médica dividida entre médicos dentistas generalistas e especialistas",
    ],
  },
  users: [
    {
      key: "owner",
      name: "Dr. Tiago Silva",
      email: "tiago@saudelisboa.demo",
      role: "admin",
      isProvider: true,
      title: "Diretor Clínico & Médico Dentista",
    },
    {
      key: "operator",
      name: "Inês Costa",
      email: "ines@saudelisboa.demo",
      role: "agent",
      isProvider: false,
      title: "Coordenação de Pacientes & Receção",
    },
    {
      key: "dentist1",
      name: "Dr. Manuel Ferreira",
      email: "manuel@saudelisboa.demo",
      role: "agent",
      isProvider: true,
      title: "Especialista em Implantologia e Cirurgia Oral",
    },
    {
      key: "dentist2",
      name: "Dra. Sofia Martins",
      email: "sofia@saudelisboa.demo",
      role: "agent",
      isProvider: true,
      title: "Especialista em Ortodontia e Estética Dentária",
    },
  ],
  services: [
    { name: "Consulta de avaliação inicial", slug: "consulta-inicial", durationMinutes: 30, description: "Exame clínico com ortopantomografia digital", color: "#0284c7" },
    { name: "Destartarização e polimento", slug: "limpieza-dental", durationMinutes: 60, description: "Higiene oral profunda com tecnologia Air-Flow", color: "#10b981" },
    { name: "Branqueamento dentário em consultório", slug: "blanqueamiento-dental", durationMinutes: 90, description: "Sessão intensiva com fotoativação LED", color: "#f59e0b" },
    { name: "Implante dentário unitário", slug: "implante-dental", durationMinutes: 120, description: "Colocação cirúrgica de implante osteointegrado", color: "#6366f1" },
    { name: "Consulta de controlo pós-tratamento", slug: "control-post-tratamiento", durationMinutes: 30, description: "Avaliação da cicatrização e manutenção", color: "#64748b" },
  ],
  pipeline: {
    name: "Tratamentos Dentários",
    slug: "tratamentos-odontologicos",
    stages: [
      { name: "Novo contacto", slug: "nuevo_contacto", position: 1 },
      { name: "Primeira conversa", slug: "primera_conversacion", position: 2 },
      { name: "Interessado", slug: "interesado", position: 3 },
      { name: "Consulta agendada", slug: "consulta_agendada", position: 4 },
      { name: "Tratamento aceite", slug: "tratamiento_vendido", position: 5, isWon: true },
      { name: "Paciente regular", slug: "paciente_recurrente", position: 6, isWon: true },
    ],
  },
  contacts: [
    {
      name: "Miguel Oliveira",
      phoneNumber: "+351912345678",
      email: "miguel.oliveira@example.pt",
      status: "new",
      stageSlug: "nuevo_contacto",
      interest: "Branqueamento dentário",
      tags: ["estetica", "novo-contacto"],
      conversationMessages: [
        { direction: "inbound", body: "Olá, bom dia. Gostaria de saber os valores para branqueamento dentário na vossa clínica em Lisboa e se fazem avaliação primeiro.", hoursAgo: 4 },
        { direction: "outbound", body: "Olá Miguel! Muito gosto. Na Clínica Saúde Lisboa realizamos uma consulta de avaliação prévia para analisar a sensibilidade e o tom pretendido. Quer agendar para esta semana?", hoursAgo: 3 },
        { direction: "inbound", body: "Sim, com certeza. Tem vaga de manhã com o Dr. Tiago Silva?", hoursAgo: 2 },
      ],
    },
    {
      name: "Beatriz Rocha",
      phoneNumber: "+351934567890",
      email: "beatriz.rocha@example.pt",
      status: "new",
      stageSlug: "interesado",
      interest: "Implante dentário",
      tags: ["implantologia", "proposta-em-aberto"],
      conversationMessages: [
        { direction: "inbound", body: "Boa tarde Inês, estive na consulta com o Dr. Manuel Ferreira. Gostaria de saber se o plano de pagamento pode ser fracionado em mensalidades.", hoursAgo: 28 },
        { direction: "outbound", body: "Olá Beatriz! Sim, dispomos de planos sem juros até 12 meses para os tratamentos de implantologia. Podemos formalizar no início do tratamento.", hoursAgo: 24 },
        { direction: "inbound", body: "Perfeito, agrada-me a proposta. Podemos avançar com o agendamento da cirurgia.", hoursAgo: 14 },
      ],
    },
    {
      name: "Rodrigo Santos",
      phoneNumber: "+351961239876",
      email: "rodrigo.santos@example.pt",
      status: "won",
      stageSlug: "paciente_recurrente",
      interest: "Revisão e limpeza",
      tags: ["paciente-regular", "higiene"],
      conversationMessages: [
        { direction: "inbound", body: "Olá Inês, recebi a notificação para a minha consulta de higiene oral semestral com a Dra. Sofia Martins.", hoursAgo: 50 },
        { direction: "outbound", body: "Olá Rodrigo! Exatamente. Temos vaga na sexta-feira às 15:30. Dá-lhe jeito?", hoursAgo: 45 },
        { direction: "inbound", body: "Sim, fica perfeito. Obrigado pela atenção.", hoursAgo: 40 },
      ],
    },
  ],
  appointments: [
    {
      eventTypeSlug: "consulta-inicial",
      patientName: "Miguel Oliveira",
      providerKey: "owner",
      daysOffset: 1,
      localHour: 10,
      localMinute: 30,
      durationMinutes: 30,
      status: "confirmed",
      notes: "Consulta inicial de diagnóstico e avaliação estética com Dr. Tiago Silva.",
    },
    {
      eventTypeSlug: "implante-dental",
      patientName: "Beatriz Rocha",
      providerKey: "dentist1",
      daysOffset: 3,
      localHour: 14,
      localMinute: 0,
      durationMinutes: 120,
      status: "scheduled",
      notes: "Cirurgia de implante osteointegrado com Dr. Manuel Ferreira.",
    },
    {
      eventTypeSlug: "limpieza-dental",
      patientName: "Rodrigo Santos",
      providerKey: "dentist2",
      daysOffset: 4,
      localHour: 15,
      localMinute: 30,
      durationMinutes: 60,
      status: "scheduled",
      notes: "Destartarização e polimento profilático com Dra. Sofia Martins.",
    },
    {
      eventTypeSlug: "control-post-tratamiento",
      patientName: "Rodrigo Santos",
      providerKey: "owner",
      daysOffset: -60,
      localHour: 11,
      localMinute: 0,
      durationMinutes: 30,
      status: "completed",
      notes: "Consulta de controlo anterior realizada com sucesso pelo Dr. Tiago Silva.",
    },
  ],
};

export default portugalDentalProfile;
