/**
 * scripts/demo/profiles/dental-clinic/colombia.ts
 *
 * Sales Demo Profile — Dental Clinic Colombia 🇨🇴
 */

import type { DemoProfile } from "../types";

export const colombiaDentalProfile: DemoProfile = {
  id: "dental-clinic-colombia",
  category: "dental-clinic",
  country: "CO",
  flag: "🇨🇴",
  orgName: "Clínica Sonrisa Bogotá",
  legalName: "Clínica Sonrisa Bogotá S.A.S.",
  slug: "clinica-sonrisa-bogota",
  language: "es",
  timezone: "America/Bogota",
  industry: "Dental Clinic",
  scenario: {
    title: "Clínica Odontológica Integral Bogotá",
    description: "Demostración de flujo comercial completo para clínicas dentales privadas: captación por WhatsApp, calificación en pipeline y agenda multiespecialista.",
    keyHighlights: [
      "Inbox WhatsApp con 3 estados: nuevo contacto, negociación activa y paciente regular",
      "Funil de 6 etapas odontológicas adaptado a conversión de tratamientos",
      "Agenda con citas futuras y concluidas divididas entre la directora y especialistas",
    ],
  },
  users: [
    {
      key: "owner",
      name: "Dra. Laura Martínez",
      email: "laura@sonrisabogota.demo",
      role: "admin",
      isProvider: true,
      title: "Directora Médica & Odontóloga",
    },
    {
      key: "operator",
      name: "Carolina Pérez",
      email: "carolina@sonrisabogota.demo",
      role: "agent",
      isProvider: false,
      title: "Operadora & Recepción",
    },
    {
      key: "dentist1",
      name: "Dr. Andrés Gómez",
      email: "andres@sonrisabogota.demo",
      role: "agent",
      isProvider: true,
      title: "Especialista en Implantología",
    },
    {
      key: "dentist2",
      name: "Dra. Sofía Torres",
      email: "sofia@sonrisabogota.demo",
      role: "agent",
      isProvider: true,
      title: "Especialista en Estética Dental",
    },
  ],
  services: [
    { name: "Consulta inicial de valoración", slug: "consulta-inicial", durationMinutes: 30, description: "Diagnóstico inicial y plan de tratamiento", color: "#0284c7" },
    { name: "Limpieza dental profunda", slug: "limpieza-dental", durationMinutes: 60, description: "Profilaxis y remoción ultrasónica de sarro", color: "#10b981" },
    { name: "Blanqueamiento dental LED", slug: "blanqueamiento-dental", durationMinutes: 90, description: "Tratamiento estético en 2 sesiones con lámpara LED", color: "#f59e0b" },
    { name: "Implante dental unitario", slug: "implante-dental", durationMinutes: 120, description: "Cirugía de colocación de implante de titanio", color: "#6366f1" },
    { name: "Control post tratamiento", slug: "control-post-tratamiento", durationMinutes: 30, description: "Revisión clínica de evolución y ajuste", color: "#64748b" },
  ],
  pipeline: {
    name: "Tratamientos Odontológicos",
    slug: "tratamientos-odontologicos",
    stages: [
      { name: "Nuevo contacto", slug: "nuevo_contacto", position: 1 },
      { name: "Primera conversación", slug: "primera_conversacion", position: 2 },
      { name: "Interesado", slug: "interesado", position: 3 },
      { name: "Consulta agendada", slug: "consulta_agendada", position: 4 },
      { name: "Tratamiento vendido", slug: "tratamiento_vendido", position: 5, isWon: true },
      { name: "Paciente recurrente", slug: "paciente_recurrente", position: 6, isWon: true },
    ],
  },
  contacts: [
    {
      name: "Carlos Rodríguez",
      phoneNumber: "+573001234567",
      email: "carlos.rodriguez@example.co",
      status: "new",
      stageSlug: "nuevo_contacto",
      interest: "Blanqueamiento dental",
      tags: ["blanqueamiento", "lead-nuevo"],
      conversationMessages: [
        { direction: "inbound", body: "Hola, buenos días. Quisiera pedir información sobre el blanqueamiento dental en Bogotá, ¿cuántas sesiones son y qué cuidados requiere?", hoursAgo: 4 },
        { direction: "outbound", body: "¡Hola Carlos! Qué gusto saludarte. En Clínica Sonrisa Bogotá realizamos blanqueamiento LED profesional en 2 sesiones con excelentes resultados. ¿Te gustaría agendar una consulta inicial de valoración para revisar tu caso?", hoursAgo: 3.5 },
        { direction: "inbound", body: "Sí, perfecto. Me queda bien en horas de la mañana con la Dra. Laura Martínez.", hoursAgo: 3 },
      ],
    },
    {
      name: "Mariana López",
      phoneNumber: "+573009876543",
      email: "mariana.lopez@example.co",
      status: "new",
      stageSlug: "interesado",
      interest: "Implante dental",
      tags: ["implante", "negociacion-activa"],
      conversationMessages: [
        { direction: "inbound", body: "Buenas tardes, estoy cotizando un implante dental para una muela inferior que perdí hace un tiempo.", hoursAgo: 48 },
        { direction: "outbound", body: "Hola Mariana, bienvenida. El Dr. Andrés Gómez es nuestro implantólogo especialista y puede valorar tu tomografía y hueso para indicarte la mejor alternativa.", hoursAgo: 46 },
        { direction: "inbound", body: "Excelente. ¿Manejan planes de financiamiento con tarjeta o cuotas mensuales?", hoursAgo: 24 },
        { direction: "outbound", body: "Sí Mariana, contamos con planes hasta 12 cuotas sin interés. ¿Te gustaría agendar la valoración este viernes?", hoursAgo: 12 },
      ],
    },
    {
      name: "Juan Pérez",
      phoneNumber: "+573105558899",
      email: "juan.perez@example.co",
      status: "won",
      stageSlug: "paciente_recurrente",
      interest: "Control post implante",
      tags: ["paciente-activo", "implante-concluido"],
      conversationMessages: [
        { direction: "inbound", body: "Hola Carolina, hace dos semanas el Dr. Andrés me colocó el implante y todo ha sanado muy bien. Ya toca mi cita de control.", hoursAgo: 72 },
        { direction: "outbound", body: "¡Qué gran noticia Juan! Me alegra mucho. Te confirmo la cita de control con el Dr. Andrés Gómez para verificar la osteointegración.", hoursAgo: 70 },
        { direction: "inbound", body: "Allí estaré puntual. Muchas gracias.", hoursAgo: 68 },
      ],
    },
  ],
  appointments: [
    {
      eventTypeSlug: "consulta-inicial",
      patientName: "Carlos Rodríguez",
      providerKey: "owner",
      daysOffset: 1,
      localHour: 9,
      localMinute: 0,
      durationMinutes: 30,
      status: "confirmed",
      notes: "Consulta inicial de valoración estética para Carlos Rodríguez.",
    },
    {
      eventTypeSlug: "implante-dental",
      patientName: "Mariana López",
      providerKey: "dentist1",
      daysOffset: 2,
      localHour: 10,
      localMinute: 30,
      durationMinutes: 120,
      status: "scheduled",
      notes: "Valoración quirúrgica y estudio óseo para implante molar con Dr. Andrés Gómez.",
    },
    {
      eventTypeSlug: "blanqueamiento-dental",
      patientName: "Carlos Rodríguez",
      providerKey: "dentist2",
      daysOffset: 4,
      localHour: 15,
      localMinute: 0,
      durationMinutes: 90,
      status: "scheduled",
      notes: "Sesión 1 de blanqueamiento dental LED con Dra. Sofía Torres.",
    },
    {
      eventTypeSlug: "control-post-tratamiento",
      patientName: "Juan Pérez",
      providerKey: "dentist1",
      daysOffset: -15,
      localHour: 11,
      localMinute: 0,
      durationMinutes: 30,
      status: "completed",
      notes: "Revisión post-quirúrgica concluida exitosamente por Dr. Andrés Gómez.",
    },
  ],
};

export default colombiaDentalProfile;
