import { Language, VideoContent } from './types';

export const LOCALIZED_CONTENT: Record<Language, VideoContent> = {
  es: {
    intro: {
      badge: 'DESKCOMM CRM · DEMO INTERACTIVA',
      title: 'De la primera conversación a la próxima acción',
      subtitle: 'Todo el flujo comercial y de atención de tu clínica en un solo espacio de trabajo.',
      features: ['WhatsApp Multicanal', 'Embudo CRM', 'Agenda Médica', 'Gestión de Equipo'],
    },
    inbox: {
      badge: '01 · BANDEJA DE ENTRADA',
      headline: 'Los mensajes de WhatsApp llegan organizados a todo tu equipo',
      subtitle: 'Historial completo del paciente, etiquetas clínicas y derivación inmediata sin perder contexto.',
      callout: 'WhatsApp Oficial · Contexto en tiempo real',
      patientName: 'Carlos Rodríguez',
      patientMessage: 'Hola, quisiera información sobre el blanqueamiento dental. ¿Tienen turnos disponibles?',
      agentResponse: '¡Hola Carlos! Sí, realizamos blanqueamiento LED en 2 sesiones. ¿Deseas agendar con la Dra. Laura Martínez?',
      patientReply: 'Sí, perfecto. Me queda bien en horas de la mañana con la Dra. Laura Martínez.',
      doctorName: 'Dra. Laura Martínez',
    },
    crm: {
      badge: '02 · PIPELINE COMERCIAL',
      headline: 'Cada conversación se convierte en una oportunidad visible',
      subtitle: 'Arrastra y avanza tratamientos por etapas sin perder ningún prospecto en el camino.',
      callout: 'Tratamientos Odontológicos · $ 450.000 COP',
      pipelineName: 'Tratamientos Odontológicos',
      stageFrom: 'Nuevo contacto',
      stageTo: 'Consulta agendada',
      dealName: 'Carlos Rodríguez — Blanqueamiento dental',
      dealValue: '$ 450.000 COP',
    },
    agenda: {
      badge: '03 · AGENDA INTELIGENTE',
      headline: 'Citas confirmadas y sincronizadas con los especialistas',
      subtitle: 'Turnos asignados por doctor, horario y tipo de tratamiento con recordatorios automáticos.',
      callout: 'Jueves 24 de sep · 11:00 AM · Dra. Laura Martínez',
      dateText: 'Jueves 24 de sep',
      appointmentTitle: 'Carlos Rodríguez — Blanqueamiento LED',
      specialistText: 'Dra. Laura Martínez (Odontología Estética)',
      statusConfirmed: 'Confirmada',
    },
    team: {
      badge: '04 · EQUIPO Y COLABORACIÓN',
      headline: 'Claridad total: quién atiende, quién deriva y quién cierra',
      subtitle: 'Roles definidos, métricas de atención y trabajo conjunto sin superposición de tareas.',
      callout: '4 profesionales activos · Control de accesos',
      roleAdmin: 'Administrador',
      roleAgent: 'Especialista / Atención',
      accountabilityTag: 'Responsable asignado',
    },
    outro: {
      badge: 'EXPERIENCIA INTERACTIVA 1-CLICK',
      headline: 'Prueba la demo tú mismo ahora',
      subtitle: 'Entornos sintéticos reales e interactivos listos en 1 clic para Colombia, México, España y Portugal.',
      ctaButton: 'Comenzar demostración interactiva →',
      features: [
        'Sin registro ni tarjeta',
        'Sin conectar tu WhatsApp',
        'Datos sintéticos aislados',
        'Acceso completo por 48h',
      ],
      url: 'demo.deskcomm.autocora.com.br/demo',
    },
  },
  pt: {
    intro: {
      badge: 'DESKCOMM CRM · DEMO INTERATIVA',
      title: 'Da primeira conversa à próxima ação',
      subtitle: 'Todo o fluxo comercial e de atendimento da sua clínica em um único espaço de trabalho.',
      features: ['WhatsApp Multicanal', 'Funil CRM', 'Agenda Médica', 'Gestão de Equipe'],
    },
    inbox: {
      badge: '01 · CAIXA DE ENTRADA',
      headline: 'As mensagens de WhatsApp chegam organizadas para toda a equipe',
      subtitle: 'Histórico completo do paciente, etiquetas clínicas e transferência ágil sem perder contexto.',
      callout: 'WhatsApp Oficial · Contexto em tempo real',
      patientName: 'Carlos Rodríguez',
      patientMessage: 'Olá, gostaria de informações sobre clareamento dental. Há horários disponíveis?',
      agentResponse: 'Olá Carlos! Sim, realizamos clareamento LED em 2 sessões. Gostaria de agendar com a Dra. Laura Martínez?',
      patientReply: 'Sim, perfeito. Fica ótimo pela manhã com a Dra. Laura Martínez.',
      doctorName: 'Dra. Laura Martínez',
    },
    crm: {
      badge: '02 · FUNIL COMERCIAL',
      headline: 'Cada conversa se transforma em uma oportunidade visível',
      subtitle: 'Arraste e avance tratamentos por etapas sem deixar nenhum lead esquecido no caminho.',
      callout: 'Tratamentos Odontológicos · R$ 1.800',
      pipelineName: 'Tratamentos Odontológicos',
      stageFrom: 'Novo contato',
      stageTo: 'Consulta agendada',
      dealName: 'Carlos Rodríguez — Clareamento dental',
      dealValue: 'R$ 1.800',
    },
    agenda: {
      badge: '03 · AGENDA INTELIGENTE',
      headline: 'Consultas confirmadas e sincronizadas com os especialistas',
      subtitle: 'Horários organizados por profissional e procedimento com confirmação automática.',
      callout: 'Quinta 24 de set · 11:00 · Dra. Laura Martínez',
      dateText: 'Quinta 24 de set',
      appointmentTitle: 'Carlos Rodríguez — Clareamento LED',
      specialistText: 'Dra. Laura Martínez (Dentística Restauradora)',
      statusConfirmed: 'Confirmada',
    },
    team: {
      badge: '04 · EQUIPE E COLABORAÇÃO',
      headline: 'Clareza total: quem atende, quem encaminha e quem fecha',
      subtitle: 'Níveis de permissão, visibilidade de responsabilidade e atendimento coordenado.',
      callout: '4 profissionais ativos · Controle de acesso',
      roleAdmin: 'Administrador',
      roleAgent: 'Especialista / Atendimento',
      accountabilityTag: 'Responsável atribuído',
    },
    outro: {
      badge: 'EXPERIÊNCIA INTERATIVA EM 1 CLIQUE',
      headline: 'Experimente a demonstração agora',
      subtitle: 'Ambientes sintéticos reais prontos em 1 clique para Colômbia, México, Espanha e Portugal.',
      ctaButton: 'Iniciar demonstração interativa →',
      features: [
        'Sem cadastro nem cartão',
        'Sem conectar seu WhatsApp',
        'Dados sintéticos isolados',
        'Acesso completo por 48h',
      ],
      url: 'demo.deskcomm.autocora.com.br/demo',
    },
  },
  en: {
    intro: {
      badge: 'DESKCOMM CRM · INTERACTIVE DEMO',
      title: 'From the first conversation to the next action',
      subtitle: 'Your clinic’s complete customer and commercial operations in one clean workspace.',
      features: ['Omnichannel WhatsApp', 'CRM Pipelines', 'Medical Scheduling', 'Team Collaboration'],
    },
    inbox: {
      badge: '01 · TEAM INBOX',
      headline: 'WhatsApp messages arrive organized for your whole team',
      subtitle: 'Complete patient history, clinical tags, and instant handoffs without losing context.',
      callout: 'Official WhatsApp · Real-time context',
      patientName: 'Carlos Rodríguez',
      patientMessage: 'Hello, I would like information regarding teeth whitening sessions. Any openings this week?',
      agentResponse: 'Hello Carlos! Yes, we perform LED whitening in 2 sessions. Would you like an appointment with Dr. Laura?',
      patientReply: 'Yes, perfect. Morning time with Dr. Laura Martínez works best for me.',
      doctorName: 'Dr. Laura Martínez',
    },
    crm: {
      badge: '02 · SALES PIPELINE',
      headline: 'Every conversation becomes a clear commercial opportunity',
      subtitle: 'Track treatment stages visually without messy disconnected spreadsheets.',
      callout: 'Dental Treatments · $ 450.000 COP',
      pipelineName: 'Dental Treatments',
      stageFrom: 'New Contact',
      stageTo: 'Appointment Scheduled',
      dealName: 'Carlos Rodríguez — Teeth Whitening',
      dealValue: '$ 450.000 COP',
    },
    agenda: {
      badge: '03 · SMART AGENDA',
      headline: 'Confirmed appointments linked to patients and specialists',
      subtitle: 'Dedicated doctor columns, custom treatment durations, and calendar sync.',
      callout: 'Thursday Sep 24 · 11:00 AM · Dr. Laura Martínez',
      dateText: 'Thursday Sep 24',
      appointmentTitle: 'Carlos Rodríguez — LED Whitening',
      specialistText: 'Dr. Laura Martínez (Cosmetic Dentistry)',
      statusConfirmed: 'Confirmed',
    },
    team: {
      badge: '04 · TEAM OWNERSHIP',
      headline: 'Clear accountability: who attends, who assigns, and who closes',
      subtitle: 'Permission tiers, workload balancing, and transparent team collaboration.',
      callout: '4 active specialists · Role controls',
      roleAdmin: 'Administrator',
      roleAgent: 'Specialist / Attendant',
      accountabilityTag: 'Assigned Owner',
    },
    outro: {
      badge: '1-CLICK INTERACTIVE DEMO',
      headline: 'Try the live demo yourself right now',
      subtitle: 'Instant disposable sandbox environments ready in 1 click for CO, MX, ES, and PT.',
      ctaButton: 'Launch Interactive Demo →',
      features: [
        'No signup or credit card',
        'No WhatsApp connection needed',
        'Safe isolated synthetic data',
        'Full 48-hour access',
      ],
      url: 'demo.deskcomm.autocora.com.br/demo',
    },
  },
};

export const getLocalizedContent = (lang: Language = 'es'): VideoContent => {
  return LOCALIZED_CONTENT[lang] || LOCALIZED_CONTENT.es;
};
