import { Language, VideoContent } from './types';

export const LOCALIZED_CONTENT: Record<Language, VideoContent> = {
  es: {
    intro: {
      badge: 'DESKCOMM CRM · DEMO INTERACTIVA',
      title: 'De la primera conversación a la próxima acción',
      subtitle: 'Todo el flujo comercial y de atención de tu clínica en un solo espacio de trabajo.',
      features: ['Canal de WhatsApp', 'Embudo CRM', 'Agenda del Equipo', 'Control de Acceso'],
    },
    inbox: {
      badge: '01 · BANDEJA DE ENTRADA',
      headline: 'Los mensajes de WhatsApp llegan organizados a todo tu equipo',
      subtitle: 'Historial completo del paciente, etiquetas clínicas y derivación inmediata sin perder contexto.',
      callout: 'Canal de WhatsApp conectado · Contexto en tiempo real',
      patientName: 'Carlos Rodríguez',
      treatmentTag: 'Blanqueamiento dental LED',
      specialistLabel: 'Especialista: Dra. Laura Martínez',
      handoffBadge: 'Derivación ágil',
      doctorName: 'Dra. Laura Martínez',
      channelBadge: 'WhatsApp',
    },
    crm: {
      badge: '02 · PIPELINE COMERCIAL',
      headline: 'Cada conversación se convierte en una oportunidad visible',
      subtitle: 'Arrastra y avanza tratamientos por etapas sin perder ningún prospecto en el camino.',
      callout: 'Tratamientos Odontológicos · $ 450.000 COP',
      pipelineName: 'Tratamientos Odontológicos',
      stageFrom: 'Nuevo contacto',
      stageTo: 'Consulta agendada',
      dealName: 'Carlos Rodríguez — Blanqueamiento dental',
      dealValue: '$ 450.000 COP',
      dealPhone: '+57 300 123 4567 · Dra. Laura Martínez',
      movingLabel: 'Moviendo oportunidad…',
      timeLabel: 'hace instantes',
      nextActionTitle: 'Próxima acción definida',
      nextActionSubtitle: 'Consulta agendada para el 24 de septiembre',
      nextActionBadge: 'Seguimiento activo',
    },
    agenda: {
      badge: '03 · AGENDA INTELIGENTE',
      headline: 'Gestión de citas y disponibilidad del equipo',
      subtitle: 'Turnos asignados por doctor, horario y tipo de tratamiento con seguimiento organizado.',
      callout: 'Jueves 24 de sep · 11:00 AM · Dra. Laura Martínez',
      dateText: 'Jueves 24 de sep',
      appointmentTitle: 'Carlos Rodríguez — Blanqueamiento LED',
      specialistText: 'Dra. Laura Martínez (Odontología Estética)',
      statusConfirmed: 'Confirmada',
      notificationTitle: 'Notificación de cita',
      notificationSubtitle: 'Aviso de cita programada para el paciente',
      notificationBadge: 'Seguimiento',
    },
    team: {
      badge: '04 · EQUIPO Y COLABORACIÓN',
      headline: 'Claridad total: quién atiende, quién deriva y quién cierra',
      subtitle: 'Roles definidos, métricas de atención y trabajo conjunto sin superposición de tareas.',
      callout: '4 profesionales activos · Control de accesos',
      coordinationTitle: 'Atención Coordinada',
      coordinationSubtitle: '4 profesionales activos en la clínica',
      coordinationBadge: 'Sin duplicidad',
      accessControlTitle: 'Control de Permisos',
      accessControlSubtitle: 'Roles de administración y agentes',
      accessControlBadge: 'Seguro por diseño',
      accountabilityTag: 'Responsable asignado',
    },
    outro: {
      badge: 'DEMO INTERACTIVA EN 1 CLIC',
      headline: 'Prueba la demo tú mismo ahora',
      subtitle: 'Explora un entorno demostrativo con datos sintéticos para Colombia, México, España y Portugal.',
      ctaButton: 'Comenzar demostración interactiva →',
      features: [
        'Sin registro ni tarjeta',
        'Sin conectar tu WhatsApp',
        'Datos sintéticos aislados',
        'Acceso completo por 48h',
      ],
      url: 'demo.deskcomm.autocora.com.br/demo',
      launchingText: 'Iniciando…',
      oneClickBadge: '1 clic',
    },
  },
  pt: {
    intro: {
      badge: 'DESKCOMM CRM · DEMO INTERATIVA',
      title: 'Da primeira conversa à próxima ação',
      subtitle: 'Todo o fluxo comercial e de atendimento da sua clínica em um único espaço de trabalho.',
      features: ['Canal de WhatsApp', 'Funil CRM', 'Agenda da Equipe', 'Controle de Acesso'],
    },
    inbox: {
      badge: '01 · CAIXA DE ENTRADA',
      headline: 'As mensagens de WhatsApp chegam organizadas para toda a equipe',
      subtitle: 'Histórico completo do paciente, etiquetas clínicas e transferência ágil sem perder contexto.',
      callout: 'Canal de WhatsApp conectado · Contexto em tempo real',
      patientName: 'Carlos Rodríguez',
      treatmentTag: 'Clareamento dental LED',
      specialistLabel: 'Especialista: Dra. Laura Martínez',
      handoffBadge: 'Transferência ágil',
      doctorName: 'Dra. Laura Martínez',
      channelBadge: 'WhatsApp',
    },
    crm: {
      badge: '02 · FUNIL COMERCIAL',
      headline: 'Cada conversa se transforma em uma oportunidade visível',
      subtitle: 'Arraste e avance tratamentos por etapas sem deixar nenhum lead esquecido no caminho.',
      callout: 'Tratamentos Odontológicos · R$ 1.800',
      pipelineName: 'Tratamentos Odontológicos',
      stageFrom: 'Novo contato',
      stageTo: 'Consulta agendada',
      dealName: 'Carlos Rodríguez — Clareamento dental',
      dealValue: 'R$ 1.800',
      dealPhone: '+57 300 123 4567 · Dra. Laura Martínez',
      movingLabel: 'Movendo oportunidade…',
      timeLabel: 'agora há pouco',
      nextActionTitle: 'Próxima ação definida',
      nextActionSubtitle: 'Consulta agendada para 24 de setembro',
      nextActionBadge: 'Acompanhamento ativo',
    },
    agenda: {
      badge: '03 · AGENDA INTELIGENTE',
      headline: 'Gestão de consultas e disponibilidade da equipe',
      subtitle: 'Horários organizados por profissional e procedimento com acompanhamento centralizado.',
      callout: 'Quinta 24 de set · 11:00 · Dra. Laura Martínez',
      dateText: 'Quinta 24 de set',
      appointmentTitle: 'Carlos Rodríguez — Clareamento LED',
      specialistText: 'Dra. Laura Martínez (Dentística Restauradora)',
      statusConfirmed: 'Confirmada',
      notificationTitle: 'Notificação de consulta',
      notificationSubtitle: 'Aviso de consulta programada para o paciente',
      notificationBadge: 'Acompanhamento',
    },
    team: {
      badge: '04 · EQUIPE E COLABORAÇÃO',
      headline: 'Clareza total: quem atende, quem encaminha e quem fecha',
      subtitle: 'Níveis de permissão, visibilidade de responsabilidade e atendimento coordenado.',
      callout: '4 profissionais ativos · Controle de acesso',
      coordinationTitle: 'Atendimento Coordenado',
      coordinationSubtitle: '4 profissionais ativos na clínica',
      coordinationBadge: 'Sem duplicidade',
      accessControlTitle: 'Controle de Permissões',
      accessControlSubtitle: 'Papéis de administrador e atendentes',
      accessControlBadge: 'Seguro por design',
      accountabilityTag: 'Responsável atribuído',
    },
    outro: {
      badge: 'DEMO INTERATIVA EM 1 CLIQUE',
      headline: 'Experimente a demonstração agora',
      subtitle: 'Explore um ambiente demonstrativo com dados sintéticos para Colômbia, México, Espanha e Portugal.',
      ctaButton: 'Iniciar demonstração interativa →',
      features: [
        'Sem cadastro nem cartão',
        'Sem conectar seu WhatsApp',
        'Dados sintéticos isolados',
        'Acesso completo por 48h',
      ],
      url: 'demo.deskcomm.autocora.com.br/demo',
      launchingText: 'Iniciando…',
      oneClickBadge: '1 clique',
    },
  },
  en: {
    intro: {
      badge: 'DESKCOMM CRM · INTERACTIVE DEMO',
      title: 'From the first conversation to the next action',
      subtitle: 'Your clinic’s complete customer and commercial operations in one clean workspace.',
      features: ['WhatsApp Channel', 'CRM Pipeline', 'Team Calendar', 'Access Controls'],
    },
    inbox: {
      badge: '01 · TEAM INBOX',
      headline: 'WhatsApp messages arrive organized for your whole team',
      subtitle: 'Complete patient history, clinical tags, and instant handoffs without losing context.',
      callout: 'Connected WhatsApp Channel · Real-time context',
      patientName: 'Carlos Rodríguez',
      treatmentTag: 'LED Teeth Whitening',
      specialistLabel: 'Specialist: Dr. Laura Martínez',
      handoffBadge: 'Smooth Handoff',
      doctorName: 'Dr. Laura Martínez',
      channelBadge: 'WhatsApp',
    },
    crm: {
      badge: '02 · SALES PIPELINE',
      headline: 'Every conversation becomes a clear commercial opportunity',
      subtitle: 'Track treatment stages visually without messy disconnected spreadsheets.',
      callout: 'Dental Treatments · $ 450.000 COP',
      pipelineName: 'Dental Treatments',
      stageFrom: 'New Contact',
      stageTo: 'Appointment Scheduled',
      dealName: 'Carlos Rodríguez — Teeth Whitening',
      dealValue: '$ 450.000 COP',
      dealPhone: '+57 300 123 4567 · Dr. Laura Martínez',
      movingLabel: 'Moving opportunity…',
      timeLabel: 'just now',
      nextActionTitle: 'Next action defined',
      nextActionSubtitle: 'Consultation booked for September 24',
      nextActionBadge: 'Active Follow-up',
    },
    agenda: {
      badge: '03 · SMART AGENDA',
      headline: 'Appointment management and team schedule',
      subtitle: 'Dedicated doctor columns, custom treatment durations, and organized follow-up.',
      callout: 'Thursday Sep 24 · 11:00 AM · Dr. Laura Martínez',
      dateText: 'Thursday Sep 24',
      appointmentTitle: 'Carlos Rodríguez — LED Whitening',
      specialistText: 'Dr. Laura Martínez (Cosmetic Dentistry)',
      statusConfirmed: 'Confirmed',
      notificationTitle: 'Appointment notification',
      notificationSubtitle: 'Scheduled appointment notice for patient',
      notificationBadge: 'Follow-up',
    },
    team: {
      badge: '04 · TEAM OWNERSHIP',
      headline: 'Clear accountability: who attends, who assigns, and who closes',
      subtitle: 'Permission tiers, workload balancing, and transparent team collaboration.',
      callout: '4 active specialists · Access control',
      coordinationTitle: 'Coordinated Care',
      coordinationSubtitle: '4 active clinical specialists',
      coordinationBadge: 'No Duplication',
      accessControlTitle: 'Access Controls',
      accessControlSubtitle: 'Admin and agent roles with full workspace',
      accessControlBadge: 'Secure by design',
      accountabilityTag: 'Assigned Owner',
    },
    outro: {
      badge: '1-CLICK INTERACTIVE DEMO',
      headline: 'Try the interactive demo yourself now',
      subtitle: 'Explore a realistic sandbox environment with synthetic data for CO, MX, ES, and PT.',
      ctaButton: 'Launch Interactive Demo →',
      features: [
        'No signup or credit card',
        'No WhatsApp connection needed',
        'Safe isolated synthetic data',
        'Full 48-hour access',
      ],
      url: 'demo.deskcomm.autocora.com.br/demo',
      launchingText: 'Starting…',
      oneClickBadge: '1-Click',
    },
  },
};

export const getLocalizedContent = (lang: Language = 'es'): VideoContent => {
  return LOCALIZED_CONTENT[lang] || LOCALIZED_CONTENT.es;
};
